### ISSUE TITLE
Any plans to support running simulators via Sweetpad launch.json?

### ISSUE THREAD

**Issue by N-Joy-Shadow** [sweetpad-dev/sweetpad#27]
Opening Sweetpad and running the simulator or running it with commands is too much work. Also, the process of deciding what to do with an already open simulator makes the mouse move. I would like to see the existing functionality of pressing f5 to launch with a preset value in launch.json.

**Comment by hyzyla** [comment]
Could you describe your workflow in more details? I'm trying to understand how better to implement that

**Comment by N-Joy-Shadow** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/958131f7-7c64-4098-91fd-05c65a8c3a52"> <br/>
Sorry for the delay in replying. I've been busy lately and didn't get back to you<br/>
I want to skip the process and restart as shown in the picture above

<img width="188" alt="image" src="https://github.com/user-attachments/assets/823fd390-d5b2-41c9-9c68-df46fbbb6cd1">

I don't know much about vscode extension, but I think you could add restart and pause buttons similar to the photo above, or use the debug and run function in vscode itself to run the simulator.

**Comment by hyzyla** [comment]
Previous weekend I updated the way how debugger works.  So basically it will attach to running app as in previous versions, but it also launches app on simulator using preLaunchTask. I can't say that it works ideally, but at least it should simplify first setup. 

I think I'll try to find out how to make stop and restart commands work after launching debugger. Maybe this or next month. Because currently I don't have any idea how to do it 

1. https://github.com/sweetpad-dev/sweetpad/blob/main/docs/wiki/debug.md

**Comment by N-Joy-Shadow** [comment]
If I have an existing iOS app running, will the debugger connect to it? Do I need to press the stop or disconnect button to restart it?

**Comment by hyzyla** [comment]
> If I have an existing iOS app running, will the debugger connect to it? 

@N-Joy-Shadow, I've just checked and found that if you need to connect to an already running application, you can use this config in your `launch.json` without building applicaiton (`"preLaunchTask": "sweetpad: launch"`):

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "sweetpad-lldb",
      "request": "launch",
      "name": "Attach to iOS app (SweetPad)"
    }
  ]
}
```

In that case, the extension tries to find the path to the last launched app `build.lastLaunchedAppPath` in the extension state and uses that path as a parameter for the CodeLLDB extension. So, as you may guess, to use that option, you must launch your application using the extension: either via the sidebar or with a command like 'Sweetpad: Build & Run (Launch).'

<hr/>
 
> Do I need to press the stop or disconnect button to restart it?

After trying different options, it seems that currently, it doesn't work so well. Here’s a breakdown of what happens if you press those buttons on the panel:

 - If you have `"preLaunchTask": "sweetpad: launch"` in your launch.json:
       -  🔄 — The app will be built and launched again, but only once 🫤.
       - 🔌 — The debugger will just disconnect, and the next time you try to start a debugging session, it will just connect to the currently running app.
       -  🟥 — This button will stop the debugger, stop the app, and stop the preLaunchTask task.
 - If you don't have `"preLaunchTask": "sweetpad: launch"` in your launch.json:
       -  🔄 — The app will simply be closed 🫤.
       - 🔌 — The debugger will just disconnect, and the next time you try to start a debugging session, it will just connect to the currently running app.
        - 🟥 — This button will stop the debugger, stop the app, and stop the preLaunchTask task.
        
For me everything work quite broken, except 🔌 button, which works as expected. Do you have any ideas how to improve debugging? I can't promise I'll be able to implement this, but I'll at least give it a try
